import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Award, CheckCircle2, AlertTriangle, ArrowRight, BarChart3, RotateCcw, AlertCircle } from 'lucide-react';
import { api } from '../services/api';

export default function ReportPage() {
  const { sessionId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    async function fetchReport() {
      setLoading(true);
      setError('');
      try {
        const data = await api.getSessionReport(sessionId);
        setReport(data);
      } catch (err) {
        setError(err.message || 'Report is generating or session has not yet concluded.');
      } finally {
        setLoading(false);
      }
    }
    fetchReport();
  }, [sessionId]);

  if (loading) {
    return (
      <div className="app-container" style={{ textAlign: 'center', padding: '5rem 1.5rem' }}>
        <h2 style={{ fontSize: '1.8rem', marginBottom: '1rem' }}>Compiling Executive Report...</h2>
        <p style={{ color: 'var(--text-secondary)' }}>The critic and evaluator are summarizing your performance rubrics.</p>
      </div>
    );
  }

  return (
    <div className="app-container" style={{ maxWidth: '900px', padding: '3rem 1.5rem' }}>
      <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
        <div className="badge badge-emerald" style={{ marginBottom: '1rem', padding: '0.4rem 0.9rem' }}>
          <Award size={14} /> Session Complete
        </div>
        <h1 style={{ fontSize: '2.4rem', marginBottom: '0.5rem' }}>Interview Performance Report</h1>
        <p style={{ color: 'var(--text-secondary)' }}>
          Detailed rubric evaluation generated by the AI critic and orchestrator engine.
        </p>
      </div>

      {error && (
        <div style={{
          padding: '1rem',
          background: 'rgba(239, 68, 68, 0.15)',
          border: '1px solid rgba(239, 68, 68, 0.3)',
          borderRadius: '10px',
          color: '#FCA5A5',
          marginBottom: '2rem',
          textAlign: 'center',
        }}>
          {error}
        </div>
      )}

      {/* Overall Score Card */}
      <div className="glass-panel" style={{
        padding: '2.5rem',
        textAlign: 'center',
        marginBottom: '2rem',
        background: 'linear-gradient(135deg, rgba(18, 26, 43, 0.9) 0%, rgba(30, 41, 59, 0.7) 100%)',
        border: '1px solid rgba(16, 185, 129, 0.3)',
      }}>
        <div style={{ fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
          Overall Session Score
        </div>
        <div style={{
          fontSize: '3.75rem',
          fontWeight: 800,
          color: (report?.overall_score || 0) >= 6.0 ? 'var(--accent-emerald)' : 'var(--accent-amber)',
          fontFamily: 'var(--font-heading)',
          lineHeight: 1,
          marginBottom: '0.75rem',
        }}>
          {report?.overall_score || '0.0'} <span style={{ fontSize: '1.5rem', color: 'var(--text-muted)' }}>/ 10</span>
        </div>
        <p style={{ color: 'var(--text-secondary)', maxWidth: '600px', margin: '0 auto', fontSize: '0.95rem', lineHeight: '1.6' }}>
          {report?.summary_text || 'Completed multi-turn adaptive interview session.'}
        </p>
      </div>

      {/* Strengths & Weaknesses */}
      <div className="grid-2" style={{ marginBottom: '2rem' }}>
        <div className="glass-panel" style={{ padding: '1.75rem', borderLeft: '4px solid var(--accent-emerald)' }}>
          <h3 style={{ fontSize: '1.2rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-emerald)' }}>
            <CheckCircle2 size={20} /> Identified Strengths
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {(report?.strengths_json || ['Clear conceptual definitions', 'Confidence under probing']).map((s, idx) => (
              <li key={idx} style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: '1.4' }}>
                &bull; {s}
              </li>
            ))}
          </ul>
        </div>

        <div className="glass-panel" style={{ padding: '1.75rem', borderLeft: '4px solid var(--accent-amber)' }}>
          <h3 style={{ fontSize: '1.2rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--accent-amber)' }}>
            <AlertTriangle size={20} /> Areas for Improvement
          </h3>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {(report?.weaknesses_json || ['Deepen algorithmic complexity trade-offs', 'Address edge cases']).map((w, idx) => (
              <li key={idx} style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: '1.4' }}>
                &bull; {w}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Topic Breakdown Card */}
      {report?.topic_breakdown_json && Object.keys(report.topic_breakdown_json).length > 0 && (
        <div className="glass-panel" style={{ padding: '1.75rem', marginBottom: '2.5rem' }}>
          <h3 style={{ fontSize: '1.2rem', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <BarChart3 size={20} color="var(--accent-cyan)" /> Topic Performance Breakdown
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {Object.entries(report.topic_breakdown_json).map(([topic, score]) => (
              <div key={topic}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '0.35rem' }}>
                  <span style={{ fontWeight: 600 }}>{topic.replace(/_/g, ' ').toUpperCase()}</span>
                  <span style={{ color: Number(score) >= 6 ? 'var(--accent-emerald)' : 'var(--accent-amber)', fontWeight: 700 }}>
                    {score} / 10
                  </span>
                </div>
                <div style={{ width: '100%', height: '8px', background: 'rgba(255,255,255,0.08)', borderRadius: '4px', overflow: 'hidden' }}>
                  <div style={{
                    width: `${Math.min(100, Math.max(5, Number(score) * 10))}%`,
                    height: '100%',
                    background: Number(score) >= 6 ? 'var(--accent-emerald)' : 'var(--accent-amber)',
                    borderRadius: '4px',
                    transition: 'width 0.5s ease',
                  }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', flexWrap: 'wrap', marginBottom: '2rem' }}>
        <button
          onClick={async () => {
            try {
              const text = await api.exportSessionReport(sessionId);
              const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
              const url = URL.createObjectURL(blob);
              const link = document.createElement('a');
              link.href = url;
              link.download = `interview_report_${sessionId.slice(0, 8)}.txt`;
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
            } catch (err) {
              alert('Could not export report: ' + err.message);
            }
          }}
          className="btn btn-secondary"
          style={{ padding: '0.85rem 1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}
        >
          Export Summary Text
        </button>
        <button
          onClick={() => window.print()}
          className="btn btn-secondary"
          style={{ padding: '0.85rem 1.5rem' }}
        >
          Print / Save PDF
        </button>
        <Link to="/" className="btn btn-secondary" style={{ padding: '0.85rem 1.5rem' }}>
          <BarChart3 size={18} /> Dashboard
        </Link>
        <Link to="/mode-select" className="btn btn-primary" style={{ padding: '0.85rem 1.75rem' }}>
          <RotateCcw size={18} /> Start Another Session
        </Link>
      </div>
    </div>
  );
}

